name: Deploy to Docker
on:
  schedule:
    # Run the job every 4 hours between 7:00 and 23:00 (UTC)
    - cron: '0 7-23/4 * * *'
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Build the Docker image
      - name: Build the Docker image
        uses: docker://docker
        with:
          args: build -t ${{ secrets.DOCKER_USERNAME }}/my_repo:latest -f price-scraper-notifier/Dockerfile .
          
      # Push the Docker image to a registry
      - name: Push the Docker image
        uses: docker://docker
        with:
          login: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://hub.docker.com/repository/docker/
          repo: ${{ secrets.DOCKER_USERNAME }}/my_repo
          tag: latest
          args: push ${{ secrets.DOCKER_USERNAME }}/my_repo:latest
