name: Deploy to Docker
on:
  schedule:
    - cron: '0 7-23/6 * * *'
  push:
    branches:
      - main
env:
    DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_HUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
    VERSION: ${{ github.sha }}
    
jobs:
    publish_python:
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: 'docker-image'
            LANGUAGE: 'python'
            LANGUAGE_VERSION: 3.11.2
        steps:
            - uses: actions/checkout@v2
            - run: echo ${DOCKER_HUB_PASSWORD} | docker login --username "${DOCKER_HUB_USER}" --password-stdin
            - run: docker build . --file ${IMAGE_NAME}/Dockerfile -t ${IMAGE_NAME}
            - run: docker tag "${IMAGE_NAME}" "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
            - run: docker push "${DOCKER_HUB_NAMESPACE}/${IMAGE_NAME}:${LANGUAGE}${LANGUAGE_VERSION}-${VERSION}"
