name: CI/CD Workflow

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 7-23/6 * * *"

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my_image:latest_tag . -f /scrape/price-scraper-notifier/Dockerfile .

      - name: Push Docker image to registry
        run: docker push DOCKER_USERNAME/my_image:latest_tag
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  run:
    name: Run Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: docker run -d --name my_container DOCKER_USERNAME/my_image:latest_tag
