name: Deploy to Docker

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 7-23/6 * * *"
    
jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.11.1]
       steps:
        - uses: actions/checkout@master
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
            repository: ${{secrets.DOCKERHUB_REPO}}
            registry: https://index.docker.io/v1/
            tag_with_ref: true
            dockerfile: ./Dockerfile

        - name: Check docker installed or not
          run: docker run hello-world
        - name: Push to docker hub
          uses: docker/build-push-action/@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
            repository: ${{secrets.DOCKERHUB_REPO}}
            tag_with_ref: true
