name: CI/CD Workflow

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 7-23/6 * * *"

jobs:
  docker:
    name: Build and push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: price-scraper-notifier  # specify the correct path to the context directory
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: Run Docker container
        env: 
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: docker run -e API_TOKEN=${API_TOKEN} -e CHAT_ID=${CHAT_ID} -e SHEET_ID=${SHEET_ID} -e GOOGLE_CREDS=${GOOGLE_CREDS}
