name: price-scraper-notifier

on:
  schedule:
    - cron: '0 7-23/8 * * *' # runs “At minute 0 past every 5th hour from 7 through 24.”
    
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.2' # install the python version needed
          architecture: 'x64'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r price-scraper-notifier/requirements.txt
          
      - name: Execute py script # run main.py to get the latest data
        env: 
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python price-scraper-notifier/main.py
